jobs:

  - name: azure-dcos-manifest
    type: manifest
    steps:
      - IN: deploy-azure-basic-img
      - IN: deploy-azure-basic-img-options
    flags:
      - deploy-azure-basic

  - name: azure-dcos-deploy
    type: deploy
    method: upgrade
    steps:
      - IN: azure-dcos-manifest
      - IN: deploy-azure-basic-dcos
    flags:
      - deploy-azure-basic
